### PR TITLE
modify to work in 2.8

### PR DESCRIPTION
**Pull request by zeffii**

### CODE REVIEW

**Comment by Mnc2g** [comment]
Hello @zeffii I think also the script CCEN.py should be modified. I get error "TypeError: UILayout.operator(): error with keyword argument "icon" -  enum "LINK" not found" as a workaround I think it's enough change "LINK" to 'NONE'. Anyway I can't get it work at all. Can you help?
Thank you very much!

**Comment by zeffii** [comment]
of course i'll look at it @Mnc2g !

**Comment by zeffii** [comment]
i forgot to look at the CCEN operator altogether, it uses a few matrix multiplications and those are done with different syntax in b280.

**Comment by Mnc2g** [comment]
Thank you very much @zeffii !
Great script!

**Pull request merged**
